# Generated by Django 2.0.3 on 2018-03-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(choices=[('Água Fria', 'Água Fria'), ('Aeroclube', 'Aeroclube'), ('Altiplano', 'Altiplano'), ('Alto do Céu', 'Alto do Céu'), ('Alto do Mateus', 'Alto do Mateus'), ('Anatólia', 'Anatólia'), ('Bairro das Indústrias', 'Bairro das Indústrias'), ('Bairro dos Estados', 'Bairro dos Estados'), ('Bairro dos Ipês', 'Bairro dos Ipês'), ('Bairro dos Novais', 'Bairro dos Novais'), ('Bancários', 'Bancários'), ('Barra de Gramame', 'Barra de Gramame'), ('Bessa', 'Bessa'), ('Brisamar', 'Brisamar'), ('Cabo Branco', 'Cabo Branco'), ('Castelo Branco', 'Castelo Branco'), ('Centro', 'Centro'), ('Cidade dos Colibris', 'Cidade dos Colibris'), ('Costa do Sol', 'Costa do Sol'), ('Costa e Silva', 'Costa e Silva'), ('Cristo Redentor', 'Cristo Redentor'), ('Cruz das Armas', 'Cruz das Armas'), ('Cuiá', 'Cuiá'), ('Distrito Industrial', 'Distrito Industrial'), ('Ernesto Geisel', 'Ernesto Geisel'), ('Ernâni Sátiro', 'Ernâni Sátiro'), ('Expedicionários', 'Expedicionários'), ('Funcionários', 'Funcionários'), ('Gramame', 'Gramame'), ('Grotão', 'Grotão'), ('Ilha do Bispo', 'Ilha do Bispo'), ('Jaguaribe', 'Jaguaribe'), ('Jardim 13 de Maio', 'Jardim 13 de Maio'), ('Jardim Cidade Universitária', 'Jardim Cidade Universitária'), ('Jardim Esther', 'Jardim Esther'), ('Jardim Luna', 'Jardim Luna'), ('Jardim Mangueira', 'Jardim Mangueira'), ('Jardim Oceania', 'Jardim Oceania'), ('Jardim Planalto', 'Jardim Planalto'), ('Jardim São Paulo', 'Jardim São Paulo'), ('Jardim Veneza', 'Jardim Veneza'), ('José Américo', 'José Américo'), ('João Agripino', 'João Agripino'), ('João Paulo II', 'João Paulo II'), ('Manaíra Leste', 'Manaíra Leste'), ('Mandacaru', 'Mandacaru'), ('Mangabeira', 'Mangabeira'), ('Mata do Buraquinho', 'Mata do Buraquinho'), ('Miramar', 'Miramar'), ('Mumbaba', 'Mumbaba'), ('Mussuré', 'Mussuré'), ('Muçumagro', 'Muçumagro'), ('Oitizeiro', 'Oitizeiro'), ('Padre Zé', 'Padre Zé'), ('Paratibe', 'Paratibe'), ('Pedro Gondim', 'Pedro Gondim'), ('Penha Leste', 'Penha Leste'), ('Planalto da Boa Esperança', 'Planalto da Boa Esperança'), ('Ponta dos Seixas', 'Ponta dos Seixas'), ('Portal do Sol', 'Portal do Sol'), ('Rangel', 'Rangel'), ('Róger', 'Róger'), ('São José', 'São José'), ('Tambaú', 'Tambaú'), ('Tambauzinho', 'Tambauzinho'), ('Tambiá', 'Tambiá'), ('Torre', 'Torre'), ('Trincheiras', 'Trincheiras'), ('Valentina Figueiredo', 'Valentina Figueiredo'), ('Varadouro', 'Varadouro'), ('Varjão', 'Varjão')], max_length=80, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(choices=[('João Pessoa', 'João Pessoa')], max_length=80, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tpLog',
            field=models.CharField(choices=[('Aeroporto', 'Aeroporto'), ('Alameda', 'Alameda'), ('Área', 'Área'), ('Avenida', 'Avenida'), ('Campo', 'Campo'), ('Chácara', 'Chácara'), ('Colônia', 'Colônia'), ('Condomínio', 'Condomínio'), ('Conjunto', 'Conjunto'), ('Distrito', 'Distrito'), ('Esplanada', 'Esplanada'), ('Estação', 'Estação'), ('Estrada', 'Estrada'), ('Favela', 'Favela'), ('Fazenda', 'Fazenda'), ('Feira', 'Feira'), ('Jardim', 'Jardim'), ('Ladeira', 'Ladeira'), ('Lago', 'Lago'), ('Lagoa', 'Lagoa'), ('Largo', 'Largo'), ('Loteamento', 'Loteamento'), ('Morro', 'Morro'), ('Núcleo', 'Núcleo'), ('Parque', 'Parque'), ('Passarela', 'Passarela'), ('Pátio', 'Pátio'), ('Praça', 'Praça'), ('Quadra', 'Quadra'), ('Recanto', 'Recanto'), ('Residencial', 'Residencial'), ('Rodovia', 'Rodovia'), ('Rua', 'Rua'), ('Setor', 'Setor'), ('Sítio', 'Sítio'), ('Travessa', 'Travessa'), ('Trecho', 'Trecho'), ('Trevo', 'Trevo'), ('Vale', 'Vale'), ('Vereda', 'Vereda'), ('Via', 'Via'), ('Viaduto', 'Viaduto'), ('Viela', 'Viela'), ('Vila', 'Vila')], max_length=30, verbose_name='Tipo de Logradouro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(choices=[('PB', 'PB')], max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='zona',
            field=models.CharField(choices=[('N', 'Norte'), ('S', 'Sul'), ('L', 'Leste'), ('O', 'Oeste')], max_length=10, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='cargo',
            field=models.CharField(choices=[('Coordenador', 'Coordenador'), ('Analista', 'Analista')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(choices=[('Gasolina Comum', 'Gasolina Comum'), ('Gasolina Aditivada', 'Gasolina Aditivada'), ('Álcool Comum', 'Álcool Comum'), ('Óleo Diesel Comum', 'Óleo Diesel Comum'), ('Óleo Diesel S10', 'Óleo Diesel S10'), ('Gás Natural', 'Gás Natural')], max_length=50, verbose_name='Nome do produto'),
        ),
    ]
