# Generated by Django 2.0.3 on 2018-03-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180319_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesquisapesquisadores',
            options={'ordering': ('pesquisa',), 'verbose_name': 'Pesquisadores por Pesquisa', 'verbose_name_plural': 'Pesquisadores por Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='postoproduto',
            options={'ordering': ('posto',), 'verbose_name': 'Produtos por Posto', 'verbose_name_plural': 'Produtos por Posto'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(choices=[('Gasolina Comum', 'Gasolina Comum'), ('Gasolina Aditivada', 'Gasolina Aditivada'), ('Álcool Comum', 'Álcool Comum'), ('Óleo Diesel Comum', 'Óleo Diesel Comum'), ('Óleo Diesel S10', 'Óleo Diesel S10'), ('Gás Natural', 'Gás Natural')], max_length=50, unique=True, verbose_name='Nome do produto'),
        ),
        migrations.AlterUniqueTogether(
            name='pesquisapesquisadores',
            unique_together={('pesquisa', 'pesquisador')},
        ),
    ]
